### ISSUE TITLE
Problems encountered trying the maven guide

### ISSUE THREAD

**Issue by gcharters** [OpenLiberty/guide-maven-intro#1]
- the repo link is incorrect.  It says guide-guide-maven, but should say guide-maven.
- the directory it say to cd into is incorrect.  It says cd guide-guide-maven/start but should say guide-maven/finish.
- says "liberty-architect-webapp" but should say "liberty-archetype-webapp".
- says "project coordinate," but should say "project coordinates," (multiple examples).
- says, "version (artifactId)", but should say "version (version)" or not have the "(version)" at all.
- I found the first sentence style difficult to read, but that might just be me.  The abrupt full stop threw me. "The parent POM to this project. The parent liberty-maven-app-parent POM file defines...".  There's another example later.  I think this is because the sections are quite long so I lose track that this is a bulleted list.
- The formatting has all gone wrong after the server.xml example code.

**Comment by lauracowen** [comment]
Tested and it's fine now.
