### ISSUE TITLE
Add class to code snippets that aren't code to copy

### ISSUE THREAD

**Issue by lauracowen** [OpenLiberty/guide-maven-intro#10]
Currently, any text that is tagged as (effectively) a code snippet is displayed with a 'copy' button that appears on hover in the top right. However, some of the 'code snippets' are actually just console output or are bits of code that the user has already copied but are being called out for more detailed explanation.

I propose tagging console output as class="console" and called out bits of code snippet as class="callout".

Passed requirement to Design to see whether the styles should be any more than just removing the copy button for those classes.

**Comment by yeekangc** [comment]
We are going to tag blocks that don't need to be copied with role="no_copy".

**Comment by yeekangc** [comment]
This has been fixed.
