### ISSUE TITLE
Update Java11 download pre-req in Guides

### ISSUE THREAD

**Issue by irobins** [OpenLiberty/guide-maven-intro#130]
Right now the Java prereq in this (and other OL guides) is to https://adoptopenjdk.net/?jvmVariant=openj9
This should be replaced with https://developer.ibm.com/languages/java/semeru-runtimes/downloads

Minor observation:
"If Maven is installed properly, you see information about the Maven installation similar to the following example:"
The illustrated Java version and home is openjdk, which is fine, but different from the pre-req described (which is OpenJ9 JVM).

**Comment by gkwan-ibm** [comment]
for download, it is a dup of https://github.com/OpenLiberty/guides-common/issues/703

**Comment by gkwan-ibm** [comment]
Need to update the output at the [Installing Maven](https://openliberty.io/guides/maven-intro.html#installing-maven) section by using semeru

**Comment by gkwan-ibm** [comment]
close
- the Java prereq was updated to use the semeru download
- the maven guide was updated the mvn version output

**Comment by gkwan-ibm** [comment]
also address issue: https://github.com/OpenLiberty/guides-common/issues/897
