### ISSUE TITLE
Add a new header field for related guides

### ISSUE THREAD

**Issue by Kubik42** [OpenLiberty/guide-maven-intro#22]
There is a new header field `page-related-guides` which can be used for referencing similar guides to the current one. We should this to the existing guides.

Ex of commit: https://github.com/OpenLiberty/guide-rest-intro/commit/78b23fd023e824aa845bc218de91ab4abcc6c640
Ex on dev site (on the side and near the bottom): https://openlibertydev.mybluemix.net/guides/rest-intro.html

**Comment by evelinec** [comment]
@proubatsis can you work on fixing this issue? Consult @JunyiSun for guidance.

**Comment by evelinec** [comment]
Completed.
