### ISSUE TITLE
Re-review for maven-intro guide

### ISSUE THREAD

**Issue by Kubik42** [OpenLiberty/guide-maven-intro#23]
**What you'll learn**
- [x] "If the tests don’t pass after you’ve made a change to the application, the build fails so you know that you need to fix your code." -> change to "If the tests don’t pass after you’ve made a change, then the build will fail, indicating that you need to fix your code." Basically, the word "application" is used in every sentence of this paragraph and it kind of gets redundant.

- [x] "You will create a Maven build definition file (pom.xml) for the web application project and use it to build the web application. You will then create a simple, automated test and configure Maven to run it after building the application." -> again, "application" is used too many times here, perhaps reword it a bit differently?

**Creating a simple application**
- [x] not that this a bad thing, but for the sake of keeping guides as short as possible, change "The simple web application that you will build using Maven and Open Liberty is provided for you in the start directory so that you can focus on learning about Maven. The application uses the standard Maven directory structure. Using the standard directory structure saves you from customizing the pom.xml file later." -> "The web application that you will use in this guide has been provided for you under the `start` directory. This application uses a standard Maven directory structure, which eliminates the need to customize the pom.xml file so that Maven understands your project layout"

- ~is the diagram needed here? I think just listing the path name should be enough. Although it does look nice~ (would argue it's good to have being an intro guide on project configuration and tooling).

- ~"All the application source code, including the Open Liberty server configuration (server.xml), is in the src/main/liberty/config directory:" -> the config directory only contains the server.xml, I think this meant to say in the src/ directory.~ (suppose to say config).

**Installing Maven**
- ~"Test that Maven is installed by running the following command in a terminal:" -> should say "... following command from command line", there is no terminal on windows~ (n/a -previously addressed).

- ~"If Maven is installed properly, you should see information about the Maven installation similar to this:" -> maybe change it to this instead: "If Maven was installed successfully, you will see an output similar to the following:"~ (n/a - previously addressed). 

**Creating the project POM file**
- ~"Before you can build the project, you **need** to define ..."~ (not necessary). 

- ~"... create it **one** section at a time"~ (n/a - previously addressed).

- ~"Create the pom.xml file in the current directory (at the same level as the src directory):" -> it would be more clear to list the full path instead, something like this: "Create src/pom.xml:"~ (n/a - does not correspond with command template for guides). 

- ~is the `parent` necessary? I'm just curious because we never seem to use it outside this guide.~ (n/a - previously updated).

- ~"The Liberty Maven plugin, which gives details of the name, version, and file type of Open Liberty runtime package which it will download from the public Maven repository." -> "The Liberty Maven plugin, which gives details of the name, version, and file type of **the** Open Liberty runtime package**,** which it will download from the public Maven repository."~ (n/a - previously addressed).

~**Building the application**~
- ~"created a `.war` file in the `target` directory" -> add missing highlighting onto "target."~ **(n/a - previously addressed)**.

- ~"After the Maven build completes, you can use the server script in that Liberty installation" -> "installation  to start and stop the server. Alternatively, you can also ..."~ **(n/a - previously addressed)**.

- ~"If the server is running, running the installation can cause issues because the installation attempts to start a server. You can instead run the following command:" -> "If the server is running, rebuilding the application can cause issue because the `install` goal will attempt to start the server, which is already running. You can instead run the following command to rebuild the application and have Open Liberty automatically pick up any new changes"~ **(n/a - previously addressed)**.

- ~"This command rebuilds the application, and the running Liberty server automatically picks up the changes." -> delete since the above~ **(n/a - previously addressed)**.

**Testing the web application**

- ~the test class "EndpointIT.java" has a look of extra space, which needs to be cleaned up. The "testServlet" method also has both a try/catch block and a throws declaration, we probably don't need both?~ **(n/a - previously addressed).**

- [x] " ... to run a set of **predefined** tests"

- ~I would change "statusCode" to "actualStatusCode" and then define a new variable called "int expectedStatusCode = HttpStatus.SC_OK". This way its clear what is the expected and what is the actual result.~ **(not necessary).**

- ~perhaps change "method" to "getMethod"?~ **(not necessary).**

- ~`Endpoint.java` -> isnt this supposed to be `EndpointIT.java`?~ **(n/a - previously addressed).**

- ~"You can now run the command mvn install to rebuild the application, including the test you’ve added, run the test, and see that the test passes. " -> remove "run the test..., and see that the test passes"~ **(n/a - previously addressed).**

- ~"The Maven build takes a little longer *now* than before ..."~ **(n/a - previously addressed).**

- ~the final code snippet doesn't have any spacing in it since the source is surrounded by a single tag, it would probably be best to add newline after each tag~ **(n/a - previously addressed).**

**Comment by gkwan-ibm** [comment]
will be addressed by https://github.com/OpenLiberty/guide-maven-intro/pull/98

**Comment by gkwan-ibm** [comment]
close this issue for all item were addressed
