### ISSUE TITLE
Maven: Remove unnecessary tags in pom.xml

### ISSUE THREAD

**Issue by chyt** [OpenLiberty/guide-maven-intro#27]

**Comment by JunyiSun** [comment]
@chyt Those tags are used to refer to specific part of the pom.xml in the README.adoc.

**Comment by andrewdes** [comment]
@chyt does @JunyiSun's explanation resolve your issue? If so, can this issue be closed?

**Comment by gkwan-ibm** [comment]
@chyt, I am going to close this issue because no response for a while. If you still have issue, you may reopen, thanks
