### ISSUE TITLE
How to include third-party libraries for Open Liberty with Maven

### ISSUE THREAD

**Issue by yeekangc** [OpenLiberty/guide-maven-intro#34]
https://stackoverflow.com/questions/51311723/how-do-i-include-third-party-libraries-in-openliberty-maven-build

This is a common use case. Should consider covering this in the Maven guide.

**Comment by gkwan-ibm** [comment]
pending on https://github.com/OpenLiberty/ci.maven/issues/705

**Comment by gkwan-ibm** [comment]
LMP is supporting to add third party library for OL. Either 
- adding a new section on this guide to talk about it but requires a good use case
- or update the JPA and/or Session guides to talk about `copyDependencies` in pom.xml

**Comment by gkwan-ibm** [comment]
- The app in the maven-intro guide is too simple to add this topic.
- In the sessions guide, add a new subsection after **Configuring Hazelcast** in the **Configuring session persistence** section to talk about this topic
- In the jpa guide, add a new section after **Performing CRUD operations using JPA** section to talk about this topic

**Comment by gkwan-ibm** [comment]
close
- added a [new section](https://openliberty.io/guides/jpa-intro.html#configuring-the-derby-driver-and-the-liberty-maven-plugin) in the JPA guide to talk about copying 3rd-party libraries
- the [sessions guide](https://openliberty.io/guides/sessions.html#configuring-session-persistence-with-jcache-in-open-liberty) briefly mentions

**Comment by gkwan-ibm** [comment]
added an [answer](https://stackoverflow.com/a/78953722/5869365) to the stackoverflow question in the description
