### ISSUE TITLE
remove gory detail for stuff in the archtype

### ISSUE THREAD

**Issue by covener** [OpenLiberty/guide-maven-intro#46]
This guide seems too long by a factor of almost 10. The biggest problem is mentioning the archtype:generate at the end instead of the beginning.    Too much blockquoted XML.

**Comment by gkwan-ibm** [comment]
hi @covener, we are closing this issue because this guide was changed to use new LMP and practice. You may open an new issue if your problem still exists in this guide https://openliberty.io/guides/maven-intro.html?
