### ISSUE TITLE
User feedback

### ISSUE THREAD

**Issue by yeekangc** [OpenLiberty/guide-maven-intro#49]
In the pom.xml:
Could not find project.build.directory's value
Googled https://cwiki.apache.org/confluence/display/MAVEN/Maven+Properties+Guide

For the Liberty server:
Could not see in the servers/GettingStartedServer/apps/getting-started.war.xml folder where the app classes and xml files are
Could not see what the app structure is, the name of the servlet and there was not a link to exercise the HelloServlet
   
Tried to find the URL from the Test file:
Could not find property project.artifactId mentioned in the pom.xml
Googled but could not find a value for it

The property is used to derive the war.name property below:         
         The JUnit test has:
             public static void init() {
               String port = System.getProperty("liberty.test.port");
               String war = System.getProperty("war.name");
               URL = "http://localhost:" + port + "/" + war + "/" + "servlet";
            }
            
Could not find what war.name is looking backwards into the xml file

**Comment by yeekangc** [comment]
@gkwan-ibm @jzoght

**Comment by jzoght** [comment]
YK, 

  I found that I was reading the "Build a web application with maven" while looking at the guide-getting-started  folder.

  I like to remove my last complain about the war.name because I found it.

  I like to keep the comment about missing URL to test the app after the mvn liberty:start-server command. The link to exercise the app should be provided.

**Comment by gkwan-ibm** [comment]
> a missing URL to test the app after the mvn liberty:start-server command. The link to exercise the app should be provided.

We will fix this



> The details about how the app was deployed using the server/apps/ServletSample.war.xml file should
> have a link to explain it or go over it a bit in the guide. I am used to dropping the .war in the dropins or apps folder. I never used a app.war.xml before to deploy a liberty app.

The guides do not focus on how to use Liberty, so they do not talk about ServletSample.war.xml which is Liberty supported feature for `<looseApplication/>` (See this [doc](https://www.ibm.com/support/knowledgecenter/en/SSEQTP_liberty/com.ibm.websphere.wlp.doc/ae/rwlp_loose_applications.html))
