### ISSUE TITLE
Defect on ol.io site

### ISSUE THREAD

**Issue by MaiHameed** [OpenLiberty/guide-maven-intro#73]
As shown in the screenshot:
![image](https://user-images.githubusercontent.com/26514093/69277346-24553380-0bae-11ea-837b-3c8c2772f7c6.png)
The reference is broken in the master site: https://openliberty.io/guides/maven-intro.html#getting-started

**Comment by gkwan-ibm** [comment]
@NimG98 hope the dev mode already address it

**Comment by gkwan-ibm** [comment]
Asked Steven to take a look

**Comment by MaiHameed** [comment]
https://github.com/OpenLiberty/guide-arquillian-managed/issues/67 Same issue, another guide

**Comment by MaiHameed** [comment]
Fixed, closing
