### ISSUE TITLE
Improving Usability for this guide.

### ISSUE THREAD

**Issue by ankitagrawa** [OpenLiberty/guide-maven-intro#77]
<img width="631" alt="image" src="https://user-images.githubusercontent.com/8294670/69444838-2c80b080-0d1f-11ea-8070-61a6f335599a.png">

1) It nowhere mentions  that you need to move to start directory to make changes and run the test case again.
If you are in finish directory and make changes as suggested then you don't see the expected result.

<img width="528" alt="image" src="https://user-images.githubusercontent.com/8294670/69445047-8b462a00-0d1f-11ea-91ae-2ce015a110fe.png">

2) 
<img width="528" alt="image" src="https://user-images.githubusercontent.com/8294670/69445052-8da88400-0d1f-11ea-9671-c35ba616e171.png">

"response string" should be a hotspot. bcoz HelloSevlet.java gets highlighted but where exactly to make changes is bit confusing.

**Comment by NimG98** [comment]
Will update hotspot in devmode PR

**Comment by evelinec** [comment]
Regarding feedback point 2, this section of the guide is to trigger user to further play around with the application/test that they learn in this guide on their own, thus, we do not state the instructions very specifically. This is by design of the guide.

**Comment by ankitagrawa** [comment]
feedback addressed thanks
