### ISSUE TITLE
Revisit the need of the dependencies for Support for JDK 9 and above

### ISSUE THREAD

**Issue by gkwan-ibm** [OpenLiberty/guide-maven-intro#90]
The pom.xml requires following
```
        <!-- Support for JDK 9 and above -->
        <dependency>
            <groupId>javax.servlet</groupId>
            <artifactId>javax.servlet-api</artifactId>
            <version>4.0.1</version>
            <scope>provided</scope>
        </dependency>
    </dependencies>
```

It should be a workaround for the issue to use java9+ previously. This issue should remove the dependencies if they are not apply anymore.

**Comment by gkwan-ibm** [comment]
- fix the same on other guides

**Comment by gkwan-ibm** [comment]
- investigating

**Comment by jj-zhang** [comment]
![image](https://user-images.githubusercontent.com/24790572/80720089-6b831100-8aca-11ea-9053-fe63a832e9b4.png)

**Comment by jj-zhang** [comment]
In `HelloServelet.java`, it requeires `javax.servlet` package, while `servlet` has been removed in the `pom.xml`

**Comment by gkwan-ibm** [comment]
@jj-zhang I have no problem to remove `javax.servlet` dependency. Would you try again?
